### ISSUE TITLE
API key is missing

### ISSUE THREAD

**Issue by EngrMubasharAli** [AmauryBuguet/binance_spot#1]
hi, i got error  **Missing API key**, same API key i tried on Postman, and its working

**Comment by vtthinh** [comment]
I fixed it.
Open binance_spot_api.dart then edit BinanceSpot({String? key, String? secret}):

BinanceSpot(String? key, String? secret){
    this._apiKey = key;
    this._apiSecret = secret;
  }

**Comment by AmauryBuguet** [comment]
Hi thanks for the fix, it should be ok now. Don't hesitate to add the lib to your project like this :
```
  binance_spot:
   git: https://github.com/AmauryBuguet/binance_spot
```
in order to have the latest version (and run ```flutter pub upgrade``` when there are new commits).
