### ISSUE TITLE
After I create newOrder success then get this error

### ISSUE THREAD

**Issue by vtthinh** [AmauryBuguet/binance_spot#2]
E/flutter (32731): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter (32731): #0      new Balance.fromMap (package:binance_spot/src/common/classes.dart:9:15)
E/flutter (32731): #1      new WsAccountUpdate.fromMap.<anonymous closure> (package:binance_spot/src/common/classes.dart:46:58)
E/flutter (32731): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter (32731): #3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter (32731): #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter (32731): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter (32731): #6      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter (32731): #7      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter (32731): #8      new WsAccountUpdate.fromMap (package:binance_spot/src/common/classes.dart:46:70)
E/flutter (32731): #9      Websockets.userDataStream.<anonymous closure> (package:binance_spot/src/websocket/websockets.dart:125:32)
E/flutter (32731): #10     _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
E/flutter (32731): #11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (32731): #12     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (32731): #13     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (32731): #14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (32731): #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (32731): #16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (32731): #17     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (32731): #18     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (32731): #19     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (32731): #20     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (32731): #21     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (32731): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (32731): #23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (32731): #24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (32731): #25     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (32731): #26     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
E/flutter (32731): #27     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (32731): #28     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (32731): #29     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (32731): #30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (32731): #31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (32731): #32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (32731): #33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (32731): #34     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (32731): #35     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (32731): #36     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (32731): #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (32731): #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (32731): #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (32731): #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (32731): #41     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (32731): #42     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (32731): #43     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1150:21)
E/flutter (32731): #44     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (32731): #45     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (32731): #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (32731): #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (32731): #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (32731): #49     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (32731): #50     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (32731): #51     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
E/flutter (32731): #52     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
E/flutter (32731): #53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter (32731): #54     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (32731): #55     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (32731): #56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (32731): #57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (32731): #58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (32731): #59     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (32731): #60     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (32731): #61     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (32731): #62     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
E/flutter (32731): #63     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (32731): #64     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (32731): #65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (32731): #66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (32731): #67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (32731): #68     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (32731): #69     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (32731): #70     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (32731): #71     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
E/flutter (32731): #72     _rootRun (dart:async/zone.dart:1420:47)
E/flutter (32731): #73     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (32731): #74     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (32731): #75     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (32731): #76     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (32731): #77     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (32731): #78     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter (32731): #79     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (32731): #80     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (32731): #81     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (32731): #82     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (32731):

**Comment by AmauryBuguet** [comment]
Hi, it should be fixed now in v0.0.2, can you try again ?

**Comment by vtthinh** [comment]
Great!
Thanks for your quick help!
