### ISSUE TITLE
ERROR: Get API Key Permissions

### ISSUE THREAD

**Issue by vtthinh** [AmauryBuguet/binance_spot#3]
E/flutter (17177): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
E/flutter (17177): #0      new ApiRestrictions.fromMap (package:binance_spot/src/rest/classes.dart:1412:40)
E/flutter (17177): #1      WalletEndpoints.apiKeyPermission.<anonymous closure> (package:binance_spot/src/rest/endpoints/wallet.dart:487:57)
E/flutter (17177): #2      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (17177): #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (17177): <asynchronous suspension>

Please fix it!

**Comment by AmauryBuguet** [comment]
should be fixed now (in the last commit). The error comes when Binance doesn't send "tradingAuthorityExpirationTime" (didn't know it could do that since it is not written as optional), that is why I changed this class member to be an int? instead of an int
